'use client';

import {
  LayoutDashboard,
  ShieldAlert,
  Shield,
  Package,
  Scale,
  Building2,
  Building,
  AlertTriangle,
  ClipboardCheck,
  Clipboard,
  TrendingUp,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  Menu,
  X,
  Search,
  Bell,
  Settings,
  User,
  UserCheck,
  LogOut,
  Plus,
  Filter,
  Download,
  Upload,
  MoreVertical,
  Eye,
  Edit,
  Trash2,
  Calendar,
  Clock,
  MapPin,
  Users,
  FileText,
  FileCheck,
  FileBarChart,
  BarChart3,
  PieChart,
  Activity,
  Target,
  CheckCircle2,
  XCircle,
  AlertCircle,
  Info,
  HelpCircle,
  ExternalLink,
  Link,
  Copy,
  RefreshCw,
  Loader2,
  Sun,
  Moon,
  Home,
  List,
  Grid2X2,
  Network,
  BookOpen,
  LifeBuoy,
  MessageSquare,
  Handshake,
  Folder,
  type LucideIcon,
} from 'lucide-react';

export const Icons = {
  dashboard: LayoutDashboard,
  risk: ShieldAlert,
  asset: Package,
  compliance: Scale,
  governance: Building2,
  incident: AlertTriangle,
  audit: ClipboardCheck,
  performance: TrendingUp,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  menu: Menu,
  close: X,
  search: Search,
  bell: Bell,
  settings: Settings,
  user: User,
  'user-check': UserCheck,
  logout: LogOut,
  plus: Plus,
  filter: Filter,
  download: Download,
  upload: Upload,
  more: MoreVertical,
  view: Eye,
  edit: Edit,
  delete: Trash2,
  calendar: Calendar,
  clock: Clock,
  location: MapPin,
  'map-pin': MapPin,
  users: Users,
  document: FileText,
  file: FileText,
  'file-check': FileCheck,
  'file-chart': FileBarChart,
  barChart: BarChart3,
  chart: BarChart3,
  pieChart: PieChart,
  activity: Activity,
  target: Target,
  checkCircle: CheckCircle2,
  check: CheckCircle2,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  alert: AlertTriangle,
  info: Info,
  help: HelpCircle,
  externalLink: ExternalLink,
  link: Link,
  copy: Copy,
  refresh: RefreshCw,
  loader: Loader2,
  sun: Sun,
  moon: Moon,
  home: Home,
  list: List,
  grid: Grid2X2,
  network: Network,
  building: Building,
  shield: Shield,
  clipboard: Clipboard,
  book: BookOpen,
  'life-buoy': LifeBuoy,
  message: MessageSquare,
  handshake: Handshake,
  folder: Folder,
  contact: Users,
} as const;

export type IconName = keyof typeof Icons;

interface IconProps extends React.SVGAttributes<SVGSVGElement> {
  name: IconName;
  size?: number;
}

export function Icon({ name, size = 20, className, ...props }: IconProps) {
  const IconComponent = Icons[name];
  return <IconComponent size={size} className={className} {...props} />;
}

export function getModuleIcon(slug: string): LucideIcon {
  const iconMap: Record<string, LucideIcon> = {
    risk: ShieldAlert,
    asset: Package,
    compliance: Scale,
    governance: Building2,
    incident: AlertTriangle,
    audit: ClipboardCheck,
    performance: TrendingUp,
  };
  return iconMap[slug] || LayoutDashboard;
}

export type { LucideIcon };
